name: "Publish Core Library"

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish-core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./libs/core
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"

      - name: Setup Rust
        run: rustup --version

      - name: Build Rust Bindings (ts-rs)
        run: deno task build:rs

      - name: Publish to JSR
        run: deno publish --allow-dirty

      - name: Build NPM package
        run: deno task build:npm

      - name: Publish to NPM
        run: |
          cd ./npm
          npm --verbose publish --tag latest
